id: A777E44FD
title: Prayer of Aspiration for the Buddhist Teachings to Flourish in Taiwan
type: translation
pechas:
- ID70DDEB5
- IF5687F75
- I97805FFC
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:47:10.230748
  last_modified_at: 2023-01-04 12:47:10.230766
  collections:
  - Katok Getse Gyurme Tenpa Gyaltsen
  - Works of Tibetan Masters
alignment_to_base:
  ID70DDEB5/2CD1: 546C
  IF5687F75/5B3B: 546C
  I97805FFC/A31F: 546C
